# Generated by Django 5.2.4 on 2025-07-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewer', '0001_initial'),
    ]

    operations = [
    ]
