# Generated by Django 5.2.4 on 2025-07-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_interviewer', '0002_auto_20250728_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='ai_hint',
            field=models.TextField(blank=True, help_text='AI-generated hint for the question', null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_taken',
            field=models.IntegerField(blank=True, help_text='Time taken in seconds', null=True),
        ),
    ]
