# Generated by Django 5.2.4 on 2025-07-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_created_at_job_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this job as featured to display it prominently'),
        ),
    ]
