# Generated by Django 5.2.4 on 2025-07-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, help_text='Job requirements and qualifications', null=True),
        ),
    ]
